# Generated by Django 5.1.7 on 2025-04-19 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('url', 'URL'), ('html', 'HTML')], max_length=10)),
                ('input_data', models.TextField()),
                ('result_json', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Accessibility Analysis',
                'verbose_name_plural': 'Accessibility Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
